theme: jekyll-theme-cayman
title: brainsea - a decentralized nervous system
description: brainsea is a platform for securely recording, sharing and analysing braindata while preserving user data privacy.
