theme: jekyll-theme-cayman
title: brainsea
description: brainsea, the decentralized nervous system, is a platform for securely recording, sharing and analysing braindata while preserving user data privacy.
